version: "3.8"

services:
  application:
    container_name: perfect_pay_application
    build:
      context: ./
      dockerfile: .setup/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - "8100:80"
    networks:
      - perfect_pay_network

  mysql:
    image: mysql:5.7.29
    container_name: perfect_pay_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    networks:
      - perfect_pay_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - perfect_pay_network

networks:
  perfect_pay_network:
    driver: bridge
